org: cjkeller03
app: geocode
service: geocode

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  geocode:
    handler: handler.hello
    events:
      - httpApi:
          method: get
          path: /geocode
