org: cjkeller03
app: geocode
service: geocode

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-2

functions:
  geocode:
    handler: handler.geocode
    events:
      - httpApi:
          method: post
          path: /geocode
